codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 2%
        informational: false
    patch:
      default:
        target: 80%
        threshold: 5%

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true

flags:
  unit:
    paths:
      - tests/unit/
    carryforward: true
  integration:
    paths:
      - tests/integration/
    carryforward: true
  e2e:
    paths:
      - tests/e2e/
    carryforward: true

ignore:
  - "tests/**/*"
  - "**/__init__.py"
  - "**/conftest.py"
